# Workflow name
name: Build and Publish Storybook to GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Job steps
    steps:
      # Manual Checkout
      - uses: actions/checkout@v3

      # Set up Node
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Get branch name
        run: |
          GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV
      - uses: bahmutov/npm-install@v1
      - run: npm run build
      - run: npm run build-storybook

      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPENDABOT_TOKEN }}
          publish_dir: ./storybook-static
          destination_dir: ./${{ env.GIT_BRANCH }}
      - name: Deploy redirect 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPENDABOT_TOKEN }}
          publish_dir: ./storybook-redirect
          keep_files: true
